name: Creative Area
favicon: null
layout_spectrum: 0.2803
typography_spectrum: 0.57789
title: Web Developper Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#009ccb'
    - '#e40072'
    - '#94d5e9'
    - '#f184ba'
  brandStrength: 0.9375
  lightness: 0.5438381303101778
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
